class Book < ApplicationRecord
  belongs_to :series, optional: true
  belongs_to :publisher, optional: true

  has_many :book_authors, -> { order(:position) }, dependent: :destroy, inverse_of: :book
  has_many :authors, through: :book_authors

  has_many :book_tags, dependent: :destroy, inverse_of: :book
  has_many :tags, through: :book_tags

  has_many :book_identifiers, dependent: :destroy, inverse_of: :book

  has_many :list_entries, dependent: :nullify, inverse_of: :book
  has_many :lists, -> { distinct }, through: :list_entries

  has_many :readings, dependent: :destroy

  has_many :shelf_entries, dependent: :destroy
  has_many :shelves, -> { distinct }, through: :shelf_entries

  # Nullify rather than destroy: when a book is deleted we want the
  # kobo_synced_books rows to *survive* so the next sync per user can
  # emit a tombstone using their snapshot kobo_uuid. The sync controller
  # destroys those rows after the tombstone is delivered, completing the
  # cleanup.
  has_many :kobo_synced_books, dependent: :nullify

  before_validation :set_kobo_uuid, on: :create
  before_destroy    :delete_files_from_disk!

  validates :calibre_id, uniqueness: true, allow_nil: true
  validates :title, :path, :imported_at, presence: true
  validates :kobo_uuid, presence: true, uniqueness: true

  scope :by_title, -> { order(Arel.sql("COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE ASC")) }
  scope :recently_added, -> { order(added_at: :desc) }

  def author_names
    authors.map(&:name).join(", ")
  end

  def isbn
    book_identifiers.isbn.order(Arel.sql("CASE kind WHEN 'isbn13' THEN 0 WHEN 'isbn' THEN 1 WHEN 'isbn10' THEN 2 END")).first&.value
  end

  def cover_full_path
    if enriched_cover_path.present?
      enriched = Rails.root.join("storage", enriched_cover_path).to_s
      return enriched if File.exist?(enriched)
    end
    return nil unless cover_path.present?
    File.join(Rails.configuration.x.library_path, cover_path)
  end

  def cover_available?
    cover_full_path.present? && File.exist?(cover_full_path)
  end

  def enriched?
    last_enriched_at.present?
  end

  def epub_full_path
    return nil unless file_name.present? && file_format.present?
    File.join(Rails.configuration.x.library_path, path, "#{file_name}.#{file_format.downcase}")
  end

  def epub_downloadable?
    path = epub_full_path
    path.present? && File.exist?(path)
  end

  # Path where the pre-converted KEPUB lives — sibling of the EPUB in
  # the user's library folder. Generated by ConvertToKepubJob (eager,
  # post-ingest + backfill). Putting it alongside the EPUB means:
  #   - the user's existing library/ backup also captures KEPUBs
  #   - removing a book directory cleans up its KEPUB too
  #   - re-ingesting from library/ picks up existing KEPUBs without
  #     re-conversion
  # `.kepub.epub` is kepubify's default naming convention.
  def kepub_path
    return nil unless file_name.present?
    File.join(Rails.configuration.x.library_path, path, "#{file_name}.kepub.epub")
  end

  def kepub_available?
    path = kepub_path
    path.present? && File.exist?(path)
  end

  # Shelves owned by the given user that contain this book. has_many :shelves
  # is global (any user); this is the per-user filter we want in views.
  def shelves_for(user)
    return Shelf.none unless user
    shelves.where(user: user)
  end

  private

  # Wipe the on-disk artifacts (EPUB, KEPUB, cover, enriched cover) before
  # the DB row goes. Guarded by start_with? checks so a malformed model
  # column can't trick us into deleting outside the configured roots.
  def delete_files_from_disk!
    library_root = Rails.configuration.x.library_path
    storage_root = Rails.root.join("storage").to_s

    [ epub_full_path, kepub_path ].compact.each do |p|
      next unless p.start_with?(library_root)
      File.delete(p) if File.exist?(p)
    end
    if cover_path.present?
      lib_cover = File.join(library_root, cover_path)
      File.delete(lib_cover) if lib_cover.start_with?(library_root) && File.exist?(lib_cover)
    end
    if enriched_cover_path.present?
      enriched = File.join(storage_root, enriched_cover_path)
      File.delete(enriched) if enriched.start_with?(storage_root) && File.exist?(enriched)
    end

    book_dir = File.join(library_root, path) if path.present?
    if book_dir && book_dir.start_with?(library_root) && File.directory?(book_dir) && Dir.empty?(book_dir)
      Dir.rmdir(book_dir)
    end
  end

  # Random UUID set before validation so it's available for indexed lookup
  # immediately. Old records were backfilled with deterministic v5(id)
  # UUIDs by the migration to preserve the Kobo's cached entitlements;
  # new records get random UUIDs because nothing depends on them being
  # derivable from id anymore.
  def set_kobo_uuid
    self.kobo_uuid ||= SecureRandom.uuid
  end
end
