# One home for everything book-files-on-disk. Wraps a Book and exposes
# its EPUB, KEPUB, and cover artifacts with safe path resolution baked
# in: every returned path is guaranteed to live inside the configured
# library or storage roots, so a malformed `path` / `cover_path` column
# can't trick us into reading or deleting something outside those roots.
#
# Callers should reach for `book.assets.X` rather than computing paths
# themselves — see docs/reviews/rails-code-review.md §5 for the
# motivation (file-path logic was spread across Book, BooksController,
# Kobo controllers, and the KEPUB job; one source of truth makes the
# invariants reviewable).
class BookAssets
  def initialize(book)
    @book = book
  end

  def epub_full_path
    return nil if @book.file_name.blank? || @book.file_format.blank?
    under_library(File.join(@book.path.to_s, "#{@book.file_name}.#{@book.file_format.downcase}"))
  end

  def epub_downloadable?
    path = epub_full_path
    !!(path && File.exist?(path))
  end

  # KEPUB sibling of the EPUB. `.kepub.epub` is kepubify's default
  # naming convention. Generated by ConvertToKepubJob; co-located with
  # the EPUB so the user's library backup captures both and re-ingest
  # picks up existing KEPUBs without re-conversion.
  def kepub_path
    return nil if @book.file_name.blank? || @book.path.blank?
    under_library(File.join(@book.path, "#{@book.file_name}.kepub.epub"))
  end

  def kepub_available?
    path = kepub_path
    !!(path && File.exist?(path))
  end

  # Resolved absolute path to the cover image. Prefers an enriched cover
  # under Rails.root/storage when present and the file exists, otherwise
  # falls back to the Calibre-managed cover under the library root.
  def cover_full_path
    if @book.enriched_cover_path.present?
      enriched = under_storage(@book.enriched_cover_path)
      return enriched if enriched && File.exist?(enriched)
    end
    return nil if @book.cover_path.blank?
    under_library(@book.cover_path)
  end

  def cover_available?
    path = cover_full_path
    !!(path && File.exist?(path))
  end

  def cover_mime_type
    path = cover_full_path
    return "application/octet-stream" unless path
    case File.extname(path).downcase
    when ".png"           then "image/png"
    when ".gif"           then "image/gif"
    when ".webp"          then "image/webp"
    when ".jpg", ".jpeg"  then "image/jpeg"
    else                       "application/octet-stream"
    end
  end

  # Wipe every artifact this book owns. Called from Book#before_destroy.
  # Each delete goes through under_*() so an attacker-controlled column
  # can't redirect us outside the configured roots even if the row was
  # somehow corrupted. The book's directory is removed too if it became
  # empty.
  def delete_all!
    [ epub_full_path, kepub_path ].compact.each do |p|
      File.delete(p) if File.exist?(p)
    end
    if @book.cover_path.present?
      p = under_library(@book.cover_path)
      File.delete(p) if p && File.exist?(p)
    end
    if @book.enriched_cover_path.present?
      p = under_storage(@book.enriched_cover_path)
      File.delete(p) if p && File.exist?(p)
    end
    cleanup_empty_directory!
  end

  private

  # Resolve a relative path under the library root, refusing anything
  # that escapes via `..` or absolute components. Returns nil for
  # unsafe inputs so callers can treat that as "not available."
  def under_library(relative)
    under_root(library_root, relative)
  end

  def under_storage(relative)
    under_root(storage_root, relative)
  end

  def under_root(root, relative)
    return nil if relative.blank?
    base      = Pathname.new(root).expand_path
    candidate = base.join(relative).expand_path
    # The trailing File::SEPARATOR matters: without it, "/lib_evil"
    # would match "/lib" as a prefix even though it's a sibling, not
    # a child.
    return nil unless candidate.to_s.start_with?(base.to_s + File::SEPARATOR)
    candidate.to_s
  end

  def cleanup_empty_directory!
    return if @book.path.blank?
    dir = under_library(@book.path)
    return unless dir && File.directory?(dir) && Dir.empty?(dir)
    Dir.rmdir(dir)
  end

  def library_root
    Rails.configuration.x.library_path
  end

  def storage_root
    Rails.root.join("storage").to_s
  end
end
