class Book < ApplicationRecord
  belongs_to :series, optional: true
  belongs_to :publisher, optional: true

  has_many :book_authors, -> { order(:position) }, dependent: :destroy, inverse_of: :book
  has_many :authors, through: :book_authors

  has_many :book_tags, dependent: :destroy, inverse_of: :book
  has_many :tags, through: :book_tags

  has_many :book_identifiers, dependent: :destroy, inverse_of: :book

  has_many :list_entries, dependent: :nullify, inverse_of: :book
  has_many :lists, -> { distinct }, through: :list_entries

  has_many :readings, dependent: :destroy

  has_many :shelf_entries, dependent: :destroy
  has_many :shelves, -> { distinct }, through: :shelf_entries

  has_many :kobo_synced_books, dependent: :destroy

  before_validation :set_kobo_uuid, on: :create

  validates :calibre_id, uniqueness: true, allow_nil: true
  validates :title, :path, :imported_at, presence: true
  validates :kobo_uuid, presence: true, uniqueness: true

  scope :by_title, -> { order(Arel.sql("COALESCE(NULLIF(sort_title, ''), title) COLLATE NOCASE ASC")) }
  scope :recently_added, -> { order(added_at: :desc) }

  def author_names
    authors.map(&:name).join(", ")
  end

  def isbn
    book_identifiers.isbn.order(Arel.sql("CASE kind WHEN 'isbn13' THEN 0 WHEN 'isbn' THEN 1 WHEN 'isbn10' THEN 2 END")).first&.value
  end

  def cover_full_path
    if enriched_cover_path.present?
      enriched = Rails.root.join("storage", enriched_cover_path).to_s
      return enriched if File.exist?(enriched)
    end
    return nil unless cover_path.present?
    File.join(Rails.configuration.x.library_path, cover_path)
  end

  def cover_available?
    cover_full_path.present? && File.exist?(cover_full_path)
  end

  def enriched?
    last_enriched_at.present?
  end

  def epub_full_path
    return nil unless file_name.present? && file_format.present?
    File.join(Rails.configuration.x.library_path, path, "#{file_name}.#{file_format.downcase}")
  end

  def epub_downloadable?
    path = epub_full_path
    path.present? && File.exist?(path)
  end

  # Path where the pre-converted KEPUB lives. Generated by
  # ConvertToKepubJob (eager, post-ingest + backfill). Derived files,
  # so they live in Rails storage rather than alongside the user's
  # EPUBs in the library folder — safe to wipe, will be regenerated.
  def kepub_path
    Rails.root.join("storage", "kepub", "book_#{id}.kepub.epub").to_s
  end

  def kepub_available?
    File.exist?(kepub_path)
  end

  # Shelves owned by the given user that contain this book. has_many :shelves
  # is global (any user); this is the per-user filter we want in views.
  def shelves_for(user)
    return Shelf.none unless user
    shelves.where(user: user)
  end

  private

  # Random UUID set before validation so it's available for indexed lookup
  # immediately. Old records were backfilled with deterministic v5(id)
  # UUIDs by the migration to preserve the Kobo's cached entitlements;
  # new records get random UUIDs because nothing depends on them being
  # derivable from id anymore.
  def set_kobo_uuid
    self.kobo_uuid ||= SecureRandom.uuid
  end
end
